services:
  - type: web
    name: followup-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /live
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: RUN_RELEASE_ON_BOOT
        value: "false"
      - key: CORS_ORIGIN
        value: https://follow-up-1-5b9e.onrender.com

  - type: web
    name: followup-frontend
    runtime: static
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://follow-up-l77j.onrender.com/api
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html

databases:
  - name: followup-postgres
    plan: free
    databaseName: followup
    user: followup
